apiVersion: v1
kind: ConfigMap
metadata:
  name: blockchain-node-config
  namespace: blockchain-network
data:
  NETWORK_ID: "12345"
  SYNC_MODE: "full" # Mendownload seluruh riwayat transaksi
  VERBOSITY: "3" # Level log untuk monitoring
  # Port untuk komunikasi antar-komputer (Peer-to-Peer)
  P2P_PORT: "30303"
  # Mengaktifkan HTTP-RPC agar aplikasi luar bisa membaca data blockchain
  RPC_ENABLE: "true"
  RPC_ADDR: "0.0.0.0"
