# Secret for Blockchain Microservice

apiVersion: v1
kind: Secret
metadata:
  name: blockchain-service-secret
  namespace: blockchain-service
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbCthc3luY3BnOi8vcG9zdGdyZXM6R2o0MlJZMkk4TzQwQGJsb2NrY2hhaW4tcG9zdGdyZXMtaGVhZGxlc3MuYmxvY2tjaGFpbi1wb3N0Z3Jlcy5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL2Jsb2NrY2hhaW5fZGI=
